## Makarov Decision Process

In [ ]:
import numpy as np

states = range(9)  # 3x3 grid, 9 states
actions = ['up', 'down', 'left', 'right']
transition_probs = {
    0: {'up': 0, 'down': 3, 'left': 0, 'right': 1},
    1: {'up': 1, 'down': 4, 'left': 0, 'right': 2},
    2: {'up': 2, 'down': 5, 'left': 1, 'right': 2},
    3: {'up': 0, 'down': 6, 'left': 3, 'right': 4},
    4: {'up': 1, 'down': 7, 'left': 3, 'right': 5},
    5: {'up': 2, 'down': 8, 'left': 4, 'right': 5},
    6: {'up': 3, 'down': 6, 'left': 6, 'right': 7},
    7: {'up': 4, 'down': 7, 'left': 6, 'right': 8},
    8: {'up': 5, 'down': 8, 'left': 7, 'right': 8},
}
rewards = {
    0: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    1: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    2: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    3: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    4: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    5: {'up': 0, 'down': 1, 'left': 0, 'right': 0},
    6: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    7: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    8: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
}

# Initialize value function
V = np.zeros(len(states))
gamma = 0.9  # Discount factor
threshold = 1e-4

# Value Iteration Algorithm
def value_iteration(V, states, actions, transition_probs, rewards, gamma, threshold):
    while True:
        delta = 0
        for s in states:
            v = V[s]
            V[s] = max([rewards[s][a] + gamma * V[transition_probs[s][a]] for a in actions])
            delta = max(delta, abs(v - V[s]))
        if delta < threshold:
            break
    return V

# Find optimal value function
V = value_iteration(V, states, actions, transition_probs, rewards, gamma, threshold)

# Extract the optimal policy
policy = {}
for s in states:
    action_values = {}
    for a in actions:
        action_values[a] = rewards[s][a] + gamma * V[transition_probs[s][a]]
    policy[s] = max(action_values, key=action_values.get)

# Display the MDP
print("Markov Decision Process:")
for state in states:
    print(f"\nState: {state}")
    for action in actions:
        print(f"  Action: {action} => Next States: {transition_probs[state][action]} with Reward: {rewards[state][action]}")

# Print the optimal policy
print("\nOptimal Value Function:")
print(V)
print("\nOptimal Policy:")
for s in policy:
    print(f"State {s}: {policy[s]}")


Markov Decision Process:

State: 0
  Action: up => Next States: 0 with Reward: 0
  Action: down => Next States: 3 with Reward: 0
  Action: left => Next States: 0 with Reward: 0
  Action: right => Next States: 1 with Reward: 0

State: 1
  Action: up => Next States: 1 with Reward: 0
  Action: down => Next States: 4 with Reward: 0
  Action: left => Next States: 0 with Reward: 0
  Action: right => Next States: 2 with Reward: 0

State: 2
  Action: up => Next States: 2 with Reward: 0
  Action: down => Next States: 5 with Reward: 0
  Action: left => Next States: 1 with Reward: 0
  Action: right => Next States: 2 with Reward: 0

State: 3
  Action: up => Next States: 0 with Reward: 0
  Action: down => Next States: 6 with Reward: 0
  Action: left => Next States: 3 with Reward: 0
  Action: right => Next States: 4 with Reward: 0

State: 4
  Action: up => Next States: 1 with Reward: 0
  Action: down => Next States: 7 with Reward: 0
  Action: left => Next States: 3 with Reward: 0
  Action: right => 

## Bellman Equation


In [ ]:
import numpy as np

# Define the MDP
states = range(9)  # 3x3 grid, 9 states
actions = ['up', 'down', 'left', 'right']
transition_probs = {
    0: {'up': 0, 'down': 3, 'left': 0, 'right': 1},
    1: {'up': 1, 'down': 4, 'left': 0, 'right': 2},
    2: {'up': 2, 'down': 5, 'left': 1, 'right': 2},
    3: {'up': 0, 'down': 6, 'left': 3, 'right': 4},
    4: {'up': 1, 'down': 7, 'left': 3, 'right': 5},
    5: {'up': 2, 'down': 8, 'left': 4, 'right': 5},
    6: {'up': 3, 'down': 6, 'left': 6, 'right': 7},
    7: {'up': 4, 'down': 7, 'left': 6, 'right': 8},
    8: {'up': 5, 'down': 8, 'left': 7, 'right': 8},
}
rewards = {
    0: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    1: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    2: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    3: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    4: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    5: {'up': 0, 'down': 1, 'left': 0, 'right': 0},
    6: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    7: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
    8: {'up': 0, 'down': 0, 'left': 0, 'right': 0},
}

# Initialize value function
V = np.zeros(len(states))
gamma = 0.9  # Discount factor
threshold = 1e-4

# Bellman Update Function
def bellman_update(V, s, actions, transition_probs, rewards, gamma):
    return max([rewards[s][a] + gamma * V[transition_probs[s][a]] for a in actions])

# Value Iteration Algorithm
def value_iteration(V, states, actions, transition_probs, rewards, gamma, threshold):
    while True:
        delta = 0
        for s in states:
            v = V[s]
            V[s] = bellman_update(V, s, actions, transition_probs, rewards, gamma)
            delta = max(delta, abs(v - V[s]))
        if delta < threshold:
            break
    return V

# Find optimal value function
V = value_iteration(V, states, actions, transition_probs, rewards, gamma, threshold)

# Extract the optimal policy
policy = {}
for s in states:
    action_values = {}
    for a in actions:
        action_values[a] = rewards[s][a] + gamma * V[transition_probs[s][a]]
    policy[s] = max(action_values, key=action_values.get)

# Print the optimal policy
print("Optimal Value Function:")
print(V)
print("\nOptimal Policy:")
for s in policy:
    print(f"State {s}: {policy[s]}")


# Initialize value function
V = {s: 0 for s in states}
threshold = 1e-6

# Value Iteration
print("\nValue Iteration Process:")
for i in range(10):  # Run for a fixed number of iterations
    print(f"\nIteration {i+1}:")
    for s in states:
        v = V[s]
        V[s] = bellman_update(V, s, actions, transition_probs, rewards, gamma)
        print(f"  Updated V({s}) from {v:.2f} to {V[s]:.2f}")

print("\nOptimal Value Function:")
for state, value in V.items():
    print(f"  V({state}) = {value:.2f}")


Optimal Value Function:
[3.83648127 4.26283314 4.73654982 4.26283314 4.73654982 5.26289484
 3.83654982 4.26289484 4.73660536]

Optimal Policy:
State 0: down
State 1: down
State 2: down
State 3: right
State 4: right
State 5: down
State 6: right
State 7: right
State 8: up

Value Iteration Process:

Iteration 1:
  Updated V(0) from 0.00 to 0.00
  Updated V(1) from 0.00 to 0.00
  Updated V(2) from 0.00 to 0.00
  Updated V(3) from 0.00 to 0.00
  Updated V(4) from 0.00 to 0.00
  Updated V(5) from 0.00 to 1.00
  Updated V(6) from 0.00 to 0.00
  Updated V(7) from 0.00 to 0.00
  Updated V(8) from 0.00 to 0.90

Iteration 2:
  Updated V(0) from 0.00 to 0.00
  Updated V(1) from 0.00 to 0.00
  Updated V(2) from 0.00 to 0.90
  Updated V(3) from 0.00 to 0.00
  Updated V(4) from 0.00 to 0.90
  Updated V(5) from 1.00 to 1.81
  Updated V(6) from 0.00 to 0.00
  Updated V(7) from 0.00 to 0.81
  Updated V(8) from 0.90 to 1.63

Iteration 3:
  Updated V(0) from 0.00 to 0.00
  Updated V(1) from 0.00 to 0.81
 

## Q-Learning

In [ ]:
import numpy as np
import random

# Define the MDP (same as above)

# Q-learning parameters
alpha = 0.1  # Learning rate
gamma = 0.9  # Discount factor
epsilon = 0.1  # Exploration rate
episodes = 1000

# Initialize Q-table
Q = np.zeros((len(states), len(actions)))

# Q-learning algorithm
for episode in range(episodes):
    state = random.choice(states)
    while state != 8:  # until we reach the terminal state
        if random.uniform(0, 1) < epsilon:
            action = random.choice(actions)
        else:
            action = actions[np.argmax(Q[state])]

        next_state = transition_probs[state][action]
        reward = rewards[state][action]

        Q[state][actions.index(action)] = Q[state][actions.index(action)] + alpha * (reward + gamma * np.max(Q[next_state]) - Q[state][actions.index(action)])
        state = next_state

# Extract the optimal policy
policy = {}
for s in states:
    policy[s] = actions[np.argmax(Q[s])]

# Print the optimal policy
print("Optimal Q-values:")
print(Q)
print("\nOptimal Policy:")
for s in policy:
    print(f"State {s}: {policy[s]}")


Optimal Q-values:
[[0.36123498 0.32965619 0.4721655  0.729     ]
 [0.64021986 0.54750467 0.53012813 0.81      ]
 [0.68512039 0.9        0.58888319 0.75269662]
 [0.6561     0.09492917 0.18013861 0.22512775]
 [0.729      0.38323651 0.20374426 0.55132156]
 [0.72268256 1.         0.63411258 0.86882724]
 [0.59046093 0.17035185 0.24777436 0.14364814]
 [0.65607856 0.1557109  0.1791296  0.        ]
 [0.         0.         0.         0.        ]]

Optimal Policy:
State 0: right
State 1: right
State 2: down
State 3: up
State 4: up
State 5: down
State 6: up
State 7: up
State 8: up


In [ ]:
import numpy as np

# Define states and actions (same as before)
states = ['S1', 'S2', 'S3']
actions = ['A1', 'A2']

# Transition probabilities (same as before)
transition_probs = {
    'S1': {'A1': ['S1', 'S2'], 'A2': ['S1', 'S3']},
    'S2': {'A1': ['S1', 'S3'], 'A2': ['S2', 'S3']},
    'S3': {'A1': ['S1'], 'A2': ['S2']}
}

# Rewards for taking actions in states (same as before)
rewards = {
    'S1': {'A1': 5, 'A2': 10},
    'S2': {'A1': 2, 'A2': 0},
    'S3': {'A1': 1, 'A2': 3}
}

# Q-Learning parameters
alpha = 0.1  # Learning rate
epsilon = 0.1  # Exploration rate
num_episodes = 100

# Initialize Q-values
Q = {s: {a: 0 for a in actions} for s in states}

# Q-Learning Process
print("\nQ-Learning Process:")
for episode in range(num_episodes):
    state = np.random.choice(states)  # Start in a random state
    for _ in range(10):  # Take 10 steps in each episode
        if np.random.rand() < epsilon:  # Exploration
            action = np.random.choice(actions)
        else:  # Exploitation
            action = max(Q[state], key=Q[state].get)

        # Debugging print statement
        print(f"Current state: {state}, Action: {action}, Possible next states: {transition_probs[state][action]}")

        # Simulate a transition
        next_state = np.random.choice(transition_probs[state][action])
        reward = rewards[state][action]

        # Update Q-value
        Q[state][action] += alpha * (reward + gamma * max(Q[next_state].values()) - Q[state][action])

    # Display Q-values for the episode
    print(f"\nEpisode {episode + 1}:")
    for s in states:
        for a in actions:
            print(f"  Q({s}, {a}) = {Q[s][a]:.2f}")

# Optimal Policy
print("\nOptimal Policy:")
for s in states:
    optimal_action = max(Q[s], key=Q[s].get)
    print(f"  Policy({s}) = {optimal_action}")



Q-Learning Process:
Current state: S3, Action: A1, Possible next states: ['S1']
Current state: S3, Action: A1, Possible next states: ['S1']
Current state: S3, Action: A1, Possible next states: ['S1']
Current state: S3, Action: A1, Possible next states: ['S1']
Current state: S3, Action: A1, Possible next states: ['S1']
Current state: S3, Action: A1, Possible next states: ['S1']
Current state: S3, Action: A1, Possible next states: ['S1']
Current state: S3, Action: A1, Possible next states: ['S1']
Current state: S3, Action: A1, Possible next states: ['S1']
Current state: S3, Action: A1, Possible next states: ['S1']

Episode 1:
  Q(S1, A1) = 0.00
  Q(S1, A2) = 0.00
  Q(S2, A1) = 0.00
  Q(S2, A2) = 0.00
  Q(S3, A1) = 0.65
  Q(S3, A2) = 0.00
Current state: S1, Action: A1, Possible next states: ['S1', 'S2']
Current state: S1, Action: A1, Possible next states: ['S1', 'S2']
Current state: S1, Action: A1, Possible next states: ['S1', 'S2']
Current state: S1, Action: A1, Possible next states: ['

## Q-Learning with Temporal Difference

In [ ]:
import numpy as np
import random

# Define the MDP (same as above)
states = ['S1', 'S2', 'S3']
actions = ['A1', 'A2']

# Transition probabilities (same as before)
transition_probs = {
    'S1': {'A1': ['S1', 'S2'], 'A2': ['S1', 'S3']},
    'S2': {'A1': ['S1', 'S3'], 'A2': ['S2', 'S3']},
    'S3': {'A1': ['S1'], 'A2': ['S2']}
}

# Rewards for taking actions in states (same as before)
rewards = {
    'S1': {'A1': 5, 'A2': 10},
    'S2': {'A1': 2, 'A2': 0},
    'S3': {'A1': 1, 'A2': 3}
}


# Q-learning parameters
alpha = 0.1  # Learning rate
gamma = 0.9  # Discount factor
epsilon = 0.1  # Exploration rate
episodes = 1000

# Initialize Q-table
Q = np.zeros((len(states), len(actions)))

# Create a mapping from state names to indices
state_to_index = {state: index for index, state in enumerate(states)}

# Q-learning with Temporal Difference algorithm
for episode in range(episodes):
    state = random.choice(states)
    while state != 'S3':  # until we reach the terminal state 'S3'
        if random.uniform(0, 1) < epsilon:
            action = random.choice(actions)
        else:
            # Use state_to_index to get the correct Q-table row
            action = actions[np.argmax(Q[state_to_index[state]])]

        # Simulate a transition and get reward (You'll need to define this part based on your MDP)
        next_state = random.choice(transition_probs[state][action])
        reward = rewards[state][action]

        # Update Q-value using state_to_index
        Q[state_to_index[state]][actions.index(action)] = Q[state_to_index[state]][actions.index(action)] + alpha * (reward + gamma * np.max(Q[state_to_index[next_state]]) - Q[state_to_index[state]][actions.index(action)])

        state = next_state

# Extract the optimal policy
policy = {}
for s in states:
    policy[s] = actions[np.argmax(Q[state_to_index[s]])]

# Print the optimal policy
print("Optimal Q-values:")
print(Q)
print("\nOptimal Policy:")
for s in policy:
    print(f"State {s}: {policy[s]}")

Optimal Q-values:
[[14.90540853 17.18688646]
 [ 9.05497445  3.6424648 ]
 [ 0.          0.        ]]

Optimal Policy:
State S1: A2
State S2: A1
State S3: A1


In [ ]:
# Q-learning with Temporal Difference algorithm
for episode in range(episodes):
    state = random.choice(states)
    while state != 'S3':  # until we reach the terminal state 'S3'
        if random.uniform(0, 1) < epsilon:
            action = random.choice(actions)
        else:
            # Get the integer index of the current state
            state_index = state_index[state]

            # Use the integer index to access Q-values
            action = actions[np.argmax(Q[state_index])]

        next_state = transition_probs[state][action][0] #Select first element from the list to get a single next state
        reward = rewards[state][action]

        # Get the integer index of the next state
        next_state_index = state_to_index[next_state]

        # Update Q-value using integer indices
        Q[state_index][actions.index(action)] = Q[state_index][actions.index(action)] + alpha * (reward + gamma * np.max(Q[next_state_index]) - Q[state_index][actions.index(action)])

        state = next_state

# Extract the optimal policy using integer indices and state names
policy = {}
for state in states:
    state_index = state_to_index[state]
    policy[state] = actions[np.argmax(Q[state_index])]

# Print the optimal policy
print("Optimal Q-values:")
print(Q)
print("\nOptimal Policy:")
for s in policy:
    print(f"State {s}: {policy[s]}")

In [ ]:
# Q-learning with Temporal Difference algorithm
for episode in range(episodes):
    state = random.choice(states)
    while state != 'S3':  # until we reach the terminal state 'S3'
        if random.uniform(0, 1) < epsilon:
            action = random.choice(actions)
        else:
            # Get the integer index of the current state using state_to_index
            state_index = state_to_index[state]

            # Use the integer index to access Q-values
            action = actions[np.argmax(Q[state_index])]

        next_state = transition_probs[state][action][0] #Select first element from the list to get a single next state
        reward = rewards[state][action]

        # Get the integer index of the next state
        next_state_index = state_to_index[next_state]

        # Update Q-value using integer indices
        Q[state_index][actions.index(action)] = Q[state_index][actions.index(action)] + alpha * (reward + gamma * np.max(Q[next_state_index]) - Q[state_index][actions.index(action)])

        state = next_state

# Extract the optimal policy using integer indices and state names
policy = {}
for state in states:
    state_index = state_to_index[state]
    policy[state] = actions[np.argmax(Q[state_index])]

# Print the optimal policy
print("Optimal Q-values:")
print(Q)
print("\nOptimal Policy:")
for s in policy:
    print(f"State {s}: {policy[s]}")

In [ ]:
# Q-learning with Temporal Difference Learning
print("\nQ-Learning with Temporal Difference Process:")
for episode in range(num_episodes):
    state = np.random.choice(states)
    for _ in range(10):
        if np.random.rand() < epsilon:
            action = np.random.choice(actions)
        else:
            action = max(Q[state], key=Q[state].get)

        next_state = np.random.choice(transition_probs[state][action])
        reward = rewards[state][action]

        # Update Q-value using TD learning
        Q[state][action] += alpha * (reward + gamma * max(Q[next_state].values()) - Q[state][action])

    print(f"\nEpisode {episode + 1}:")
    for s in states:
        for a in actions:
            print(f"  Q({s}, {a}) = {Q[s][a]:.2f}")

# Display final Q-values
print("\nFinal Q-values:")
for s in states:
    for a in actions:
        print(f"  Q({s}, {a}) = {Q[s][a]:.2f}")
